# Generated by Django 3.2 on 2021-04-14 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Clients',
        ),
        migrations.RenameModel(
            old_name='NewInvoice',
            new_name='Invoices',
        ),
        migrations.RenameModel(
            old_name='Project',
            new_name='Projects',
        ),
    ]
