# Generated by Django 3.2 on 2021-04-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0003_auto_20210414_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='create_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.IntegerField(default='-'),
        ),
    ]
