# Generated by Django 3.2 on 2021-04-14 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0004_auto_20210414_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project',
            new_name='name',
        ),
    ]
