# Generated by Django 3.2 on 2021-04-14 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0005_rename_project_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='toolbox.project'),
        ),
    ]
