# Generated by Django 3.2 on 2021-04-16 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0007_alter_invoice_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(editable=False,
                                    on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.client'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.project'),
        ),
    ]
