# Generated by Django 3.2 on 2021-04-16 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0008_auto_20210416_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='toolbox.client'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolbox.project'),
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default='-')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('amount', models.FloatField(editable=False)),
                ('currency', models.CharField(editable=False, max_length=3)),
                ('client', models.ForeignKey(editable=False,
                                             on_delete=django.db.models.deletion.CASCADE, to='toolbox.client')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolbox.invoice')),
                ('project', models.ForeignKey(editable=False,
                                              on_delete=django.db.models.deletion.CASCADE, to='toolbox.project')),
            ],
        ),
    ]
