# Generated by Django 3.2 on 2021-04-17 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0009_auto_20210416_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='project',
        ),
    ]
